server:
  port: 8000

spring:
  application:
    name: gateway


zuul:
  prefix: /api     #添加路由前缀
  routes:
    item-service : /item/**






hystrix:
  metrics:
    polling-interval-ms: 2000

ribbon:
  
